name: Update IPTV list from ZeroNet

on:
  schedule:
    - cron: '0 */6 * * *'  # Se actualiza cada 6 horas
  workflow_dispatch:      # Botón para actualizar a mano

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download from ZeroNet Proxy
        run: |
          # Intentamos bajar la lista usando el proxy público de ZeroNet
          # He añadido "hashes.m3u" que suele ser el nombre estándar en ese sitio
          curl -L "https://0net.io/1JKe3VPvFe35bm1aiHdD4p1xcGCkZKhH3Q/hashes.m3u" -o lista_zero.m3u

      - name: Commit changes
        run: |
          git config --global user.name "saviobest11"
          git config --global user.email "bot@github.com"
          git add lista_zero.m3u
          git commit -m "update zeronet list" || echo "no changes"
          git push
